In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [2]:
book = pd.read_csv('Books.csv')
user = pd.read_csv('Users.csv')
rating = pd.read_csv('Ratings.csv')

C:\Users\vikra\AppData\Local\Temp\ipykernel_26112\3667942254.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv('Books.csv')

In [3]:
book.shape

(271360, 8)

In [4]:
user.shape

(278858, 3)

In [5]:
rating.shape

(1149780, 3)

In [6]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
user.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [8]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [9]:
book.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
book.dropna(inplace=True)

In [11]:
book.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            0
dtype: int64

In [12]:
book.sample(5)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
7216,0609609017,Ten Poems to Change Your Life,Roger Housden,2001,Harmony,http://images.amazon.com/images/P/0609609017.0...,http://images.amazon.com/images/P/0609609017.0...,http://images.amazon.com/images/P/0609609017.0...
241948,0671003747,MTVS ROAD RULES ROAD TRIPS,Genevieve Field,1996,MTV,http://images.amazon.com/images/P/0671003747.0...,http://images.amazon.com/images/P/0671003747.0...,http://images.amazon.com/images/P/0671003747.0...
159059,0062507915,The Great Cosmic Mother : Rediscovering the Re...,Monica Sjoo,1987,HarperSanFrancisco,http://images.amazon.com/images/P/0062507915.0...,http://images.amazon.com/images/P/0062507915.0...,http://images.amazon.com/images/P/0062507915.0...
233992,3446200770,Grammatik der SchÃ?Â¶pfung.,George Steiner,2001,Carl Hanser Verlag,http://images.amazon.com/images/P/3446200770.0...,http://images.amazon.com/images/P/3446200770.0...,http://images.amazon.com/images/P/3446200770.0...
57718,0395171199,"Best American Short Stories, 1973","Martha, Ed. Foley",1973,Houghton Mifflin Co,http://images.amazon.com/images/P/0395171199.0...,http://images.amazon.com/images/P/0395171199.0...,http://images.amazon.com/images/P/0395171199.0...

In [13]:
book['Book-Title1'] = book['Book-Title'].apply(lambda x: x.replace(" ", ""))
book['Book-Author'] = book['Book-Author'].apply(lambda x: x.replace(" ", ""))
book['Publisher'] = book['Publisher'].apply(lambda x: x.replace(" ", ""))

In [14]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Title1
0,0195153448,Classical Mythology,MarkP.O.Morford,2002,OxfordUniversityPress,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,ClassicalMythology
1,0002005018,Clara Callan,RichardBruceWright,2001,HarperFlamingoCanada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,ClaraCallan
2,0060973129,Decision in Normandy,CarloD'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,DecisioninNormandy
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,GinaBariKolata,1999,FarrarStrausGiroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,Flu:TheStoryoftheGreatInfluenzaPandemicof1918a...
4,0393045218,The Mummies of Urumchi,E.J.W.Barber,1999,W.W.Norton&amp;Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,TheMummiesofUrumchi

In [15]:
book['tags'] = book['Book-Title1']+" "+ ['book-Author']+" "+ ['Publisher']+" "+['Year-Of-Publication']

In [16]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Title1,tags
0,0195153448,Classical Mythology,MarkP.O.Morford,2002,OxfordUniversityPress,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,ClassicalMythology,ClassicalMythology book-Author Publisher Year-...
1,0002005018,Clara Callan,RichardBruceWright,2001,HarperFlamingoCanada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,ClaraCallan,ClaraCallan book-Author Publisher Year-Of-Publ...
2,0060973129,Decision in Normandy,CarloD'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,DecisioninNormandy,DecisioninNormandy book-Author Publisher Year-...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,GinaBariKolata,1999,FarrarStrausGiroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,Flu:TheStoryoftheGreatInfluenzaPandemicof1918a...,Flu:TheStoryoftheGreatInfluenzaPandemicof1918a...
4,0393045218,The Mummies of Urumchi,E.J.W.Barber,1999,W.W.Norton&amp;Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,TheMummiesofUrumchi,TheMummiesofUrumchi book-Author Publisher Year...

In [17]:
book['Image-URL-S']

0         http://images.amazon.com/images/P/0195153448.0...
1         http://images.amazon.com/images/P/0002005018.0...
2         http://images.amazon.com/images/P/0060973129.0...
3         http://images.amazon.com/images/P/0374157065.0...
4         http://images.amazon.com/images/P/0393045218.0...
                                ...
271355    http://images.amazon.com/images/P/0440400988.0...
271356    http://images.amazon.com/images/P/0525447644.0...
271357    http://images.amazon.com/images/P/006008667X.0...
271358    http://images.amazon.com/images/P/0192126040.0...
271359    http://images.amazon.com/images/P/0767409752.0...
Name: Image-URL-S, Length: 271353, dtype: object

In [18]:
book['Image-URL-M']

0         http://images.amazon.com/images/P/0195153448.0...
1         http://images.amazon.com/images/P/0002005018.0...
2         http://images.amazon.com/images/P/0060973129.0...
3         http://images.amazon.com/images/P/0374157065.0...
4         http://images.amazon.com/images/P/0393045218.0...
                                ...
271355    http://images.amazon.com/images/P/0440400988.0...
271356    http://images.amazon.com/images/P/0525447644.0...
271357    http://images.amazon.com/images/P/006008667X.0...
271358    http://images.amazon.com/images/P/0192126040.0...
271359    http://images.amazon.com/images/P/0767409752.0...
Name: Image-URL-M, Length: 271353, dtype: object

In [40]:
book['Image-URL-L'].isnull().sum()

np.int64(0)

In [20]:
book['tags'] = book['tags'].apply(lambda x: x.lower())

In [21]:
book['tags']

0         classicalmythology book-author publisher year-...
1         claracallan book-author publisher year-of-publ...
2         decisioninnormandy book-author publisher year-...
3         flu:thestoryofthegreatinfluenzapandemicof1918a...
4         themummiesofurumchi book-author publisher year...
                                ...
271355    there'sabatinbunkfive book-author publisher ye...
271356    fromonetoonehundred book-author publisher year...
271357    lilydale:thetruestoryofthetownthattalkstothede...
271358    republic(world'sclassics) book-author publishe...
271359    aguidedtourofrenedescartes'meditationsonfirstp...
Name: tags, Length: 271353, dtype: object

In [22]:
book = book.iloc[:,[0,1,7,9]]

In [23]:
book.head()

,ISBN,Book-Title,Image-URL-L,tags
0,0195153448,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...,classicalmythology book-author publisher year-...
1,0002005018,Clara Callan,http://images.amazon.com/images/P/0002005018.0...,claracallan book-author publisher year-of-publ...
2,0060973129,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...,decisioninnormandy book-author publisher year-...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...,flu:thestoryofthegreatinfluenzapandemicof1918a...
4,0393045218,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...,themummiesofurumchi book-author publisher year...

In [24]:
import nltk   # remove the like loved, loving to love only so not repeat the same word using prefix or suffix

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [25]:
book['tags'] = book['tags'].apply(stem)

book['tags']

0         classicalmytholog book-author publish year-of-...
1              claracallan book-author publish year-of-publ
2         decisioninnormandi book-author publish year-of...
3         flu:thestoryofthegreatinfluenzapandemicof1918a...
4         themummiesofurumchi book-author publish year-o...
                                ...
271355    there'sabatinbunkf book-author publish year-of...
271356    fromonetoonehundr book-author publish year-of-...
271357    lilydale:thetruestoryofthetownthattalkstothede...
271358    republic(world'sclassics) book-author publish ...
271359    aguidedtourofrenedescartes'meditationsonfirstp...
Name: tags, Length: 271353, dtype: object

In [26]:
book.head()

,ISBN,Book-Title,Image-URL-L,tags
0,0195153448,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...,classicalmytholog book-author publish year-of-...
1,0002005018,Clara Callan,http://images.amazon.com/images/P/0002005018.0...,claracallan book-author publish year-of-publ
2,0060973129,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...,decisioninnormandi book-author publish year-of...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...,flu:thestoryofthegreatinfluenzapandemicof1918a...
4,0393045218,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...,themummiesofurumchi book-author publish year-o...

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words='english')

vector = cv.fit_transform(book['tags'])

In [28]:
# # we find the angle between the movies
# due to large data the ram is required in gb so it is not useful method

# from sklearn.metrics.pairwise import cosine_similarity

# similarity = cosine_similarity(vector)

In [29]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(
    n_neighbors=6,
    metric='cosine',
    algorithm='brute'
)

model.fit(vector)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [30]:
book[book['Book-Title'] == 'Classical Mythology'].index[0]

np.int64(0)

In [35]:
def recommend(book_ob):
    index1 = book[book['Book-Title'] == book_ob].index[0]
    distances, indices = model.kneighbors(vector[index1:index1+1])

    for i in indices[0][1:]:
        print(book.iloc[i]['Book-Title'])
        print("Image:", book.iloc[i]['Image-URL-L'])

In [36]:
recommend('Decision in Normandy')

Hearts of Fire
Image: http://images.amazon.com/images/P/0451401352.01.LZZZZZZZ.jpg
Cyberhound's Internet Guide to the Coolest Stuff Out There (Cyberhound's)
Image: http://images.amazon.com/images/P/078760688X.01.LZZZZZZZ.jpg
Practical Reiki
Image: http://images.amazon.com/images/P/1855343622.01.LZZZZZZZ.jpg
Now I Lay Me Down to Sleep (Rushford, Patricia H. Helen Bradley Mysteries.)
Image: http://images.amazon.com/images/P/1556617305.01.LZZZZZZZ.jpg
Ullstein Taschenbucher: Wilde Engel
Image: http://images.amazon.com/images/P/3426608359.01.LZZZZZZZ.jpg

In [37]:
import pickle

pickle.dump(model, open('model.pkl', 'wb'))

In [38]:
import pickle

pickle.dump(vector, open('vector.pkl', 'wb'))

In [39]:
import pickle

pickle.dump(book, open('book.pkl', 'wb'))